# Generated by Django 3.0.5 on 2020-04-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='uploads/avatar/default.png', max_length=200, null=True, upload_to='uploads/avatar/%Y/%m', verbose_name='用户头像'),
        ),
    ]
